import './globals.css'
import { Rubik } from 'next/font/google'

export const dynamic = 'force-dynamic'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {children}
      </body>
    </html>
  )
}


// json-server --watch --port 4000 ./_data/db.json
// 

// npm install @supabase/auth-helpers-nextjs @supabase/supabase-js

// npm run dev - runs the app in dev mode
// npm run build - build the entire project to run in prod
// npm start - runs the built project (PRODUCTION)

// after building the application the app turn much more faster then when using the dev server

